{{- if .Values.ingress.enabled }}
apiVersion: {{ include "qt-vault.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "qt-vault.fullname" . }}
  namespace: {{ include "qt-vault.namespace" . }}
  labels: {{- include "qt-vault.labels" . | nindent 4 }}
  {{- if or .Values.ingress.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if and .Values.ingress.ingressClassName (eq "true" (include "qt-vault.supportsIngressClassname" .)) }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            {{- if eq "true" (include "qt-vault.supportsPathType" .) }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare "<1.19-0" (include "qt-vault.kubeVersion" .) }}
              serviceName: {{ include "qt-vault.fullname" . }}
              servicePort: http
              {{- else }}
              service:
                name: {{ include "qt-vault.fullname" . }}
                port:
                  name: http
              {{- end }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if eq "true" (include "qt-vault.supportsPathType" $) }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare "<1.19-0" (include "qt-vault.kubeVersion" $) }}
              serviceName: {{ include "qt-vault.fullname" $ }}
              servicePort: http
              {{- else }}
              service:
                name: {{ include "qt-vault.fullname" $ }}
                port:
                  name: http
              {{- end }}
    {{- end }}
  {{- if or .Values.ingress.tls .Values.ingress.extraTls }}
  tls:
    {{- if .Values.ingress.tls }}
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- toYaml .Values.ingress.extraTls | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
